### ISSUE TITLE
Manejo de credenciales en privada

### ISSUE THREAD

**Issue by profe-benja** [gogomezc/APP-MOVILES#17]
Manejo de credenciales en privada

https://github.com/gogomezc/APP-MOVILES/blob/de1329ea8be9fa260eb33633a15b212c180553f9/Core/src/app/services/auth.service.ts#L10C2-L11C1

Instalar dotenv para quitar las credenciales publicas

[dotenv](https://www.npmjs.com/package/dotenv)

**Comment by Ayastian** [comment]
Issue cerrado, solucionado en el siguiente commit:
https://github.com/gogomezc/APP-MOVILES/commit/147dbe7cc4ea3deb7a1a1567663b868edd1a2d70
